### ISSUE TITLE
Support for i18n comments

### ISSUE THREAD

**Issue by clicman** [thucydides-webtests/thucydides-cucumber#14]
I`m using internationalized features:

```
# language: ru
Функционал: Операции с картами

  @card1
  Сценарий: Просмотр краткой панели информации по карте
    Дано пользователь активировал демо-режим
    Когда пользователь выбирает карту "4276 **** ****
```

In reports I see: 
![Broken parsed](http://i.imgur.com/6VqcHrc.png)

Comments must be skipped.

**Comment by wakaleo** [comment]
This should work in serenity-cucumber (https://github.com/serenity-bdd/serenity-cucumber). All new work is happening on that project.
