### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by frol2103** [thucydides-webtests/thucydides-cucumber#15]
Hi,

Is this project still alive?
Is it useable?

Thanks

François

**Comment by wakaleo** [comment]
Hi,

It has been superceeded by serenity-cucumber:
https://github.com/serenity-bdd/serenity-cucumber

On 9 February 2015 at 21:42, frol2103 notifications@github.com wrote:

> Hi,
> 
> Is this project still alive?
> Is it useable?
> 
> Thanks
> 
> François
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thucydides-webtests/thucydides-cucumber/issues/15.

## 

---

John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com

---

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming _BDD/TDD Master classes_
http://wakaleo.com/training/testing-and-tdd-for-java-developers and
our _Advanced
BDD Requirements Workshops
http://wakaleo.com/training/advanced-agile-requirements-workshop_, coming
soon to _Sydney
http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses
*
and *Melbourne
http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses!_

---

**Comment by frol2103** [comment]
Merci beaucoup
